//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with and , the first terms will be:
//1,2,3,5,8,13,21,.....
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

let limit = 4000000;
let fib1 = 1;
let fib2 = 2;
let evenSum = 0;
while(fib2 <=limit){
    if(fib2 % 2 === 0){
        evenSum += fib2;
    }
    let nextF = fib1 + fib2;
    fib1 = fib2;
    fib2 = nextF;
}
console.log(evenSum);
