//Each new term in Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2.
//The first 10 terms will be:1,2,3,5,8,21,34,55,89....
//By considering the terms in Fibonacci Sequence whose values do not exceed 4 million
//find the sum of the even-valued terms.
fn main(){
    let mut result = 0;
    let mut x = 1;
    let mut y = 2;
    while x <= 4000000{
        if x%2==0{
            result += x;
        }
        x = y;
        y += x;
    }
    println!("The sum of even valued terms {:?}",result)
}
